image: debian:latest

stages:
  - lint
  - test
  - build

variables:
  WORK_DIR: /go/src/github.com/AlphaWong

services:
  - docker:dind

before_script:
 - mkdir -p $WORK_DIR
 - cd $WORK_DIR
 - ln -sf $CI_PROJECT_DIR
 - cd $CI_PROJECT_NAME

pages:
  image: golang:latest
  stage: test
  script:
    - go version
    - echo $CI_BUILD_REF
    - echo $CI_PROJECT_DIR
    - pwd
    - mkdir public
    - sh ./build.sh
    - make coveragehtml
  artifacts:
    paths:
      - public

build:
  image: docker:stable
  stage: build
  script:
    - version=$(cat version)
    - docker login -u $ACCOUNT -p $PASSWORD registry.gitlab.com
    - docker build -t registry.gitlab.com/alphawong/html2pdf .
    - docker tag registry.gitlab.com/alphawong/html2pdf registry.gitlab.com/alphawong/html2pdf:$version
    - docker push registry.gitlab.com/alphawong/html2pdf:$version
    - docker push registry.gitlab.com/alphawong/html2pdf

lint:
  image: golang:latest
  stage: lint
  allow_failure: true
  script:
    - go get -u github.com/mgechev/revive
    - revive -formatter stylish --exclude=./vendor/... ./...
